language: php

php:
- '7.1'

before_install:
  - composer self-update
  - nvm install lts/*
  - npm i -g gulp
install:
  - composer install --prefer-dist --no-dev --no-interaction
  - npm i
  
script:
  - gulp

before_deploy:
  - rm -rf release/
  - mkdir release
  - cp -avr lib release/
  - cp -avr assets release/
  - cp -avr templates release/
  - cp -avr vendor release/
  - cp srbtranslatin.php release/
  - cp readme.txt release/
  - tar -czf ./$TRAVIS_TAG.tar.gz release/*
  - zip -r ./$TRAVIS_TAG.zip release/*

deploy:
  provider: releases
  skip_cleanup: true
  file:
      - $TRAVIS_TAG.zip
      - $TRAVIS_TAG.tar.gz
  api_key:
    secure: hsIihbmeOmXGEXk7vTcccKLrNlwJXBR9Tf/G5+Ajn6MpYyV4MMdHdg8EW5GoSpoWQc4lxUgBfIjkSjwWkvI6qQz6B3dDGv8sZ9k40WfV0kJ5N5W4rPKUId316SS3dzhnuwKZSMn/QKUG/RHueUEplevlUehsmfB9KlpdxGY/gHgGHmkZStwd7mFZWXvjUdZUjHm1IkCpD7PLuJaqOgORI/DfC6MV8Gf/yQcPnzXgFp0cu4xZePzzO3gVJ63bvE54Wg7p5q5Ia9zclDgoZokE7x0S+vcFNhQj9J/OWJqY5uLvHn3Pi0HhvoozOZQxEYm7j3mR7VbYRgJsxWN4eRZRXhC8i2iM4t/Q386zFzC00AAsprouDuCr05aKuSGbp8N/kQZi0aLdECUqGbRX/evSYZqhkNQ/Upfxmw5ZXYB1hWZ6IRmT8r0eBYSk+5DgCG75yEdtWZinttaStxqDc66qlotOlnhBweRYfZODek1Lmb69uwbfZleSQRmsRFkL91n1s+qpvNEacnWocHYWv8zHeEe0P5urNQrY9sjosKsX6P6P0xyF+T4RLBWzqqpUb+qIIq5TR/zlDQ3LrkpXg0U8cF6373CYjjclCmAXdYAyZaEN3fQZHetiS/nVpjUXGU/Lj+6kTIxionsVUQttl8P6ZM7fZSnVQFDFplj+9lzTzQI=
  on:
    tags: true